name: Deploy Flutter Web to GH Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web
        run: |
          # For project pages:
          flutter build web --release --wasm --base-href "/${{ github.event.repository.name }}/"
          # If you host at the root (user.github.io), use: --base-href "/"

      - name: Add .nojekyll and 404 fallback
        run: |
          touch build/web/.nojekyll
          # Only needed if using PathUrlStrategy (no hashes):
          if [ -f build/web/index.html ]; then cp build/web/index.html build/web/404.html; fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
